<?php
/**
 * Logs viewer head scripts
 *
 * @package    BardCanvas
 * @subpackage log_viewer
 * @author     Alejandro Caballero - lava.caballero@gmail.com
 */
?>

<!-- Logs viewer head scripts -->

<script type="text/javascript" src="<?=$config->full_root_path?>/lib/jquery.scrollTo-min.js"></script>
<script type="text/javascript" src="<?=$config->full_root_path?>/log_viewer/media/functions~v<?=$config->scripts_version?>.js"></script>
<link rel="stylesheet"        href="<?=$config->full_root_path?>/log_viewer/media/styles~v<?=$config->scripts_version?>.css">

