<?php
/**
 * Logs viewer head scripts
 *
 * @package    BardCanvas
 * @subpackage log_viewer
 * @author     Alejandro Caballero - lava.caballero@gmail.com
 */
?>

<!-- Logs viewer head scripts -->

<script type="text/javascript" src="<?=$config->full_root_path?>/lib/jquery.scrollTo.js"></script>
<script type="text/javascript" src="<?=$config->full_root_path?>/log_viewer/media/functions~v1.0.6-2.js"></script>
<link rel="stylesheet"        href="<?=$config->full_root_path?>/log_viewer/media/styles~v1.1.0-4.css">

